### ISSUE TITLE
InboxData Message

### ISSUE THREAD

**Issue by Kitten-EASY** [PhoenixFire6879/Classic-Brawl#16]
Can you make InboxData?

**Comment by CrazorCLB** [comment]
Not yet but maybe one day and if you want you can join the discord we are a community ready for talking and having fun here is the invite: https://discord.gg/ZEFT5DDgTH

**Comment by archerland** [comment]
Hello, do you have other version of app??, because i cannot run it on my handphone , i think it's not supported frida in my handphone.. do you have any solution ??

**Comment by Kitten-EASY** [comment]
> Hello, do you have other version of app??, because i cannot run it on my handphone , i think it's not supported frida in my handphone.. do you have any solution ??

I think no. It needs Android 6.0+

**Comment by archerland** [comment]
Oh okay
