### ISSUE TITLE
The problem with downloading after a friendly fight

### ISSUE THREAD

**Issue by 6am6ik** [PhoenixFire6879/Classic-Brawl#20]
Hello, I have a problem. When the fight ends (I win)I click the exit and the download gets stuck at 92%, the screenshot is shown. How do you solve this? 
![Screenshot_20210206_090812_com brawlstars v26](https://user-images.githubusercontent.com/78601130/107110716-4393bb80-685b-11eb-849c-ccf51d2490b8.jpg)
![Screenshot_20210206_090816_com brawlstars v26](https://user-images.githubusercontent.com/78601130/107110718-45f61580-685b-11eb-858c-5af0baad35fd.jpg)

**Comment by Hit1ove** [comment]
I also have an error (92% stop)

**Comment by Kitten-EASY** [comment]
You need to host server on pc or other device

**Comment by 6am6ik** [comment]
> You need to host server on pc or other device

I get it, thank you.
