### ISSUE TITLE
how to update server 

### ISSUE THREAD

**Issue by gamer23232323** [PhoenixFire6879/Classic-Brawl#21]

**Comment by CrazorCLB** [comment]
Hmm  can you give more info on what you want?

**Comment by gamer23232323** [comment]
How to update server to new version brawl stars

**Comment by Kitten-EASY** [comment]
he mean how to make server for v33

**Comment by gamer23232323** [comment]
Лол чел я у тебя это спрашивал

**Comment by gamer23232323** [comment]
> he mean how to make server for v33

Чел ебать я понял если получится я кину апк и сурс сервака

**Comment by jakovmarkovanovic** [comment]
v9999 no u

**Comment by Kitten-EASY** [comment]
> > he mean how to make server for v33
> 
> Чел ебать я понял если получится я кину апк и сурс сервака

Ок

**Comment by CrazorCLB** [comment]
Learn frida do packets and bam you have a v33 server
