### ISSUE TITLE
Boxes do not open.

### ISSUE THREAD

**Issue by Mops2008wer** [PhoenixFire6879/Classic-Brawl#26]
When the box is opened, it does not open, but this is written in the console:
![Screenshot_554](https://user-images.githubusercontent.com/78369368/108543044-95295500-72f5-11eb-8719-4079f1812a41.png)

**Comment by thejulfor** [comment]
Show me Boxes.py from Logic folder

**Comment by Mops2008wer** [comment]
I didn't change anything there. (if that is a serv on version 22)

**Comment by CrazorCLB** [comment]
hmm

**Comment by CrazorCLB** [comment]
i will check that soon

**Comment by Mops2008wer** [comment]
I have already solved the problem, but I have 1 more question. How do I remove all the skins?

**Comment by CrazorCLB** [comment]
OwnHomeData
