### ISSUE TITLE
How do I start maintenance?

### ISSUE THREAD

**Issue by Mops2008wer** [PhoenixFire6879/Classic-Brawl#27]

**Comment by Mops2008wer** [comment]
+ sometimes the database crashes. When this happens the server writes this. How can I avoid this?
![Screenshot_558](https://user-images.githubusercontent.com/78369368/108622596-ebf47300-744a-11eb-9dd5-005bb6797e27.png)

**Comment by FourCinnamon0** [comment]
Cuz tinydb is trash. I made a custom database system that fixes this

**Comment by CrazorCLB** [comment]
How much player was on the server when this happen?

**Comment by Mops2008wer** [comment]
This can happen at any time, regardless of the number of players.
