### ISSUE TITLE
The server V24 is not connecting

### ISSUE THREAD

**Issue by frostyprosty** [PhoenixFire6879/Classic-Brawl#35]
The server stuck at Connecting to  server. i am already changed ip in the libgg.config.so,but server dont connect.
What im need to do ?

**Comment by 4ak34** [comment]
Hello, did you run the server as said in the readme?

**Comment by frostyprosty** [comment]
> Hello, did you run the server as said in the readme?

Yes

**Comment by frostyprosty** [comment]
What I'm need to do?

**Comment by brawler888** [comment]
ты пидор
