### ISSUE TITLE
Can't make the client app work

### ISSUE THREAD

**Issue by DomerDev** [PhoenixFire6879/Classic-Brawl#43]
The server works perfectly, but the client app can't connect to it.
According to the console log, it is listening on 0.0.0.0:9339, so I put this in libcb.config.so:

      "parameters":{
         "redirectHost": "0.0.0.0",
		 "redirectPort": "9339"
      }

Did I get something wrong?

**Comment by liviumarica** [comment]
How did you edit the libcb.config.so file?

**Comment by DomerDev** [comment]
> How did you edit the libcb.config.so file?

I'm using APK Easy Tool
