### ISSUE TITLE
MongoDB Error

### ISSUE THREAD

**Issue by Evgenie3311** [PhoenixFire6879/Classic-Brawl#52]
____                      __   _____ __
   / __ )_________ __      __/ /  / ___// /_____ ___________
  / __  / ___/ __ `/ | /| / / /   \__ \/ __/ __ `/ ___/ ___/
 / /_/ / /  / /_/ /| |/ |/ / /   ___/ / /_/ /_/ / /  (__  )
/_____/_/   \__,_/ |__/|__/_/   /____/\__/\__,_/_/  /____/

[DEBUG] Connecting to Mongo DataBase...
[ERROR] Unable to connect to Mongo server!

[Program finished]

**Comment by bobertop44** [comment]
how fix it?
