### ISSUE TITLE
I can't connect to the server

### ISSUE THREAD

**Issue by sav365** [PhoenixFire6879/Classic-Brawl#54]
Am I doing something wrong? Help please
![Screenshot_20230531-000606_1](https://github.com/PhoenixFire6934/Classic-Brawl/assets/126119979/7f9a45ee-4eac-4725-89c4-45b16e8d1d0c)
![Screenshot_20230531-000650](https://github.com/PhoenixFire6934/Classic-Brawl/assets/126119979/207bde56-e517-48f0-b3f8-81a5f5debd6d)

**Comment by SplashClick** [comment]
Who are you?

ср, 31 мая 2023 г., 02:11 sav365 ***@***.***>:
