### ISSUE TITLE
Incompatible APK file with Android 13

### ISSUE THREAD

**Issue by SORRYSPLASH** [PhoenixFire6879/Classic-Brawl#59]
So When I Opened The Edited File with the IP of the Server in the config file that is inside libs and armv7 It crashed, I tried reinstalling and that just does not help, I tried clearing cache and data and still it didn't help, But once I opened the edited file on Android 11 it didn't crashed. I tried to find some logs about the crash but I didn't find any.

The link to the app you provided that crashes:
https://mega.nz/file/OL5SAD6Q#70_56frFtBDO5DC-g1qOzuzFv4txx_rT6Sr4m49-0NA

And thank you for creating such a good project I really appreciate it.

Edit: I tried the v24 branch and it works, I wonder why it is like that...

**Comment by PhoenixFire6934** [comment]
Check the new client app: https://mega.nz/file/zDQzDYyB#V7GkrTFQpTfhTk_gOroMfdps5VFl8Lnn-CBX-bbnjlw
