### ISSUE TITLE
can you make ios client?

### ISSUE THREAD

**Issue by sashaMacos** [PhoenixFire6879/Classic-Brawl#60]
can you make ios client?

**Comment by 8-bitHacc** [comment]
I believe there's already an iOS client made by @risporce
[https://mega.nz/file/JhtyXIbB#3bWTilF2dwLHd6elsE2Tfu3WziWSQd1UsRxx42WiIBI](url)
Download this and patch your client's ip (if you know that is)

**Comment by sashaMacos** [comment]
the client says that there is an update

**Comment by 8-bitHacc** [comment]
oh well, i cant provide support with this as im not the creator of that client, you can ask @risporce on discord about it (i dont know if he'll help)

**Comment by 8-bitHacc** [comment]
@

**Comment by risporce** [comment]
This is a really old client, it's very well possible that the Frida in there is outdated + I think this client required jailbreak to function

> the client says that there is an update

**Comment by sashaMacos** [comment]
So I can't use sideloading or trollstore? I just tried other iOS clients, and they report that an update is required, maybe I'm doing something wrong? Do you have instructions for working with it?
