### ISSUE TITLE
MongoDB error

### ISSUE THREAD

**Issue by bobertop44** [PhoenixFire6879/Classic-Brawl#63]
[36m[DEBUG] Connecting to Mongo DataBase...
 [31m[ERROR] Unable to connect to Mongo server!

how fix it...

**Comment by Julav911** [comment]
Hey

**Comment by AbzBs** [comment]
@Julav911  Hey its me from New account

**Comment by AbzBs** [comment]
U know how fix it?

**Comment by AbzBs** [comment]
I am live in country where MongoDB blocked ( I used vpn to configure db) could this be the reason?

**Comment by 8-bitHacc** [comment]
Yes, this could be a reason. Classic Brawl will not be using MongoDB in future releases.
Sorry for the late response
