### ISSUE TITLE
Error: Empty host

### ISSUE THREAD

**Issue by natesworks** [PhoenixFire6879/Classic-Brawl#74]
The Updater has detected that the server is in a crashed state (error: Empty host (or extra comma in host list).).

**Comment by natesworks** [comment]
What is host list?

**Comment by 8-bitHacc** [comment]
Mongodb URL hasn't been added into the config.json file

**Comment by natesworks** [comment]
im just used to it auto working because of sqlite3 but this server has an actually good db so ye ty
